name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: want build
        shell: cmd

      - name: Run tests
        run: want test
        shell: cmd

      - name: Save binary
        uses: actions/upload-artifact@v4
        with:
          name: eu_skill_reader.exe
          path: |
            build/Release/eu_skill_reader.exe

      - name: Save binary sha512 hash
        uses: actions/upload-artifact@v4
        with:
          name: eu_skill_reader.sha512
          path: build/Release/eu_skill_reader.sha512